openapi: 3.0.3
info:
  title: Bank Argent API documentation
  description: Contains available API endpoints for accounts
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
servers:
  - url: localhost:3001
tags:
  - name: Accounts
    description: API documentation for Bank Argent accounts
paths:
  /accounts:
    get:
      tags:
        - Accounts
      summary: Get an array of all accounts
      description: Get an array of all accounts
      operationId: getAllAcounts
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Accounts'
        '400':
          description: Invalid ID supplied
        '401':
          description: Authorization not granted
        '404':
          description: Accounts not found
      security:
        - Bearer: []
  /accounts/{accountId}:
    get:
      tags:
        - Accounts
      summary: Get all informations about an account
      description: Get all informations about an account
      operationId: getAccount
      parameters:
        - name: accountId
          in: path
          schema:
            type: integer
          required: true
          description: Numeric ID of the account to get
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: Invalid ID supplied
        '401':
          description: Authorization not granted
        '404':
          description: Account not found
      security:
        - Bearer: []
  /accounts/{accountId}/transactions:
    get:
      tags:
        - Accounts
      summary: Get all transactions from an account
      description: Get all transactions from an account
      operationId: getAccountTransactions
      parameters:
        - name: accountId
          in: path
          schema:
            type: integer
          required: true
          description: Numeric ID of the account to get
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transactions'
        '400':
          description: Invalid ID supplied
        '401':
          description: Authorization not granted
        '404':
          description: Account not found
      security:
        - Bearer: []
  /accounts/{accountId}/transactions/{transactionId}:
    get:
      tags:
        - Accounts
      summary: Get a transaction from an account
      description: Get a transaction from an account
      operationId: getTransaction
      parameters:
        - name: accountId
          in: path
          schema:
            type: integer
          required: true
          description: Numeric ID of the account to get
        - name: transactionId
          in: path
          schema:
            type: integer
          required: true
          description: Numeric ID of the transaction to get
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Invalid ID supplied
        '401':
          description: Authorization not granted
        '404':
          description: Transaction not found
      security:
        - Bearer: []
    patch:
      tags:
        - Accounts
      summary: Modify a transaction from an account
      description: Modify a transaction from an account
      operationId: postTransaction
      parameters:
        - name: accountId
          in: path
          schema:
            type: integer
          required: true
          description: Numeric ID of the account to get
        - name: transactionId
          in: path
          schema:
            type: integer
          required: true
          description: Numeric ID of the transaction to modify
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  example: Food
                notes:
                  type: string
                  example: A baguette bougth at the golden sun bakery
        required: true
      responses:
        '204':
          description: No content
        '400':
          description: Bad request
        '401':
          description: Authorization not granted
        '404':
          description: Transaction not found
      security:
        - Bearer: []
components:
  schemas:
    Accounts:
      type: array
      items:
        $ref: '#/components/schemas/Account'
    Account:
      type: object
      properties:
        accountId:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Argent Bank Checking
        balance:
          type: integer
          format: int64
          example: 2082.79
    Transactions:
      type: array
      items:
        $ref: '#/components/schemas/Transaction'
    Transaction:
      type: object
      properties:
        transactionId:
          type: integer
          format: int64
          example: 100000
        accountId:
          type: integer
          format: int64
          example: 10
        date:
          type: string
          format: date
        amount:
          type: integer
          format: int64
        description:
          type: string
        balance:
          type: integer
          format: int64
        type:
          type: string
          example: Electronic
        category:
          type: string
          example: Food
        notes:
          type: string
  requestBodies:
    Accounts:
      description: Get all accounts
      content:
        application/json:
          schema:
            type: object
            items:
              $ref: '#/components/schemas/Accounts'
    Account:
      description: Get all informations from an account
      content:
        application/json:
          schema:
            type: object
            items:
              $ref: '#/components/schemas/Account'
    Transactions:
      description: Get all transactions from an account
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Transactions'
    Transaction:
      description: Description of a transaction
      content:
        application/json:
          schema:
            type: object
            items:
              $ref: '#/components/schemas/Transaction'
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
